table dim_items
	lineageTag: 31b23040-c7f9-42e8-99e8-570b80d405dc

	measure DistinctProducts =
			
			
			VAR DistinctItems = DISTINCTCOUNT(dim_items[item_id])
			
			RETURN DistinctItems
		formatString: 0
		displayFolder: Metricas Items
		lineageTag: 38955060-b0be-4005-9cfd-92666c3d3b56

	column item_id
		dataType: int64
		formatString: 0
		lineageTag: c36e0981-1856-4760-a163-a11fbdb34acf
		summarizeBy: none
		sourceColumn: item_id

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: dd8023d5-c2fa-4a03-aff9-1f67226b93d6
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	partition dim_items = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\laios\Documents\Data Analyst\PowerBI\items.xlsx"), null, true),
				    items_Sheet = Source{[Item="items",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(items_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"item_id", Int64.Type}, {"category", type text}}),
				    pattern_beer_Beer = Table.ReplaceValue(#"Changed Type","beer","Beer",Replacer.ReplaceText,{"category"}),
				    pattern_nab_Nab = Table.ReplaceValue(pattern_beer_Beer,"nab","Nab",Replacer.ReplaceText,{"category"}),
				    pattern_soda_Soda = Table.ReplaceValue(pattern_nab_Nab,"soda","Soda",Replacer.ReplaceText,{"category"}),
				    pattern_liquor_Liquor = Table.ReplaceValue(pattern_soda_Soda,"liquor","Liquor",Replacer.ReplaceText,{"category"})
				in
				    pattern_liquor_Liquor

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

