table fact_order
	lineageTag: b1bdbf33-32d4-4850-b384-16d92c5b26cd

	measure GMVTotal = ```
			SUM(fact_order[revenue])
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Metricas Fact Order
		lineageTag: d56af0db-7439-46a8-8557-401d21067227

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure MetaSeller =
			
			
			VAR MetaTotal = SUM(dim_targets[monthly_revenue_target])
			
			RETURN MetaTotal
		formatString: 0
		displayFolder: Metricas Fact Order
		lineageTag: 0f4be534-7981-46e8-9fc7-57b22263bd33

	measure OrdersQuantity =
			
			
			VAR TotalOrders = DISTINCTCOUNT(fact_order[order_id])
			
			RETURN TotalOrders
		formatString: 0
		displayFolder: Metricas Fact Order
		lineageTag: 1e8f4285-ab27-474c-bcbd-8fd8f7d3e4f5

	measure AvgRevenue = ```
			
			
			VAR SumRevenueOrders = SUM(fact_order[revenue])
			VAR OrdersDistinct = DISTINCTCOUNT(fact_order[order_id])
			VAR AVGTicket = DIVIDE(SumRevenueOrders,OrdersDistinct)
			
			RETURN AVGTicket
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Metricas Fact Order
		lineageTag: c2cad9a2-fe02-4025-a751-a3f13dd4dae6

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure MedianaTicketMedio = ```
			
			VAR TabelaPedidos = 
			    SUMMARIZE(
			        fact_order,
			        fact_order[order_id],
			        "TotalPorPedido", SUM(fact_order[revenue])
			    )
			RETURN 
			    MEDIANX(TabelaPedidos, [TotalPorPedido])
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Metricas Fact Order
		lineageTag: 7e03caca-72fb-434a-91c1-13ce4522d294

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure UsuariosDistintos =
			
			
			VAR UsersOrders = DISTINCTCOUNT(fact_order[user_id])
			
			RETURN UsersOrders
		formatString: 0
		displayFolder: Metricas Fact Order
		lineageTag: c04fcc1d-b1af-4594-af90-389bd45af23c

	measure MediaUsuariosDistintos =
			
			DIVIDE([GMVTotal],[UsuariosDistintos],0)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Metricas Fact Order
		lineageTag: d24860d3-2ac8-44c4-a0b2-7a636e83508f

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure MedianaUsuarios = ```
			
			VAR TabelaUsuarios = 
			    SUMMARIZE(
			        fact_order,
			        fact_order[user_id],
			        "VendasUsuario", SUM(fact_order[revenue]) 
			    )
			RETURN 
			    MEDIANX(TabelaUsuarios, [VendasUsuario])
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Metricas Fact Order
		lineageTag: a7c23406-7b00-41b5-8fc5-8b3e76048961

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure QuantidadeVendasProduto = ```
			
			
			VAR VendasProduto = COUNT(fact_order[order_id]) 
			
			RETURN VendasProduto
			```
		formatString: 0
		displayFolder: Metricas Fact Order
		lineageTag: aaccde07-f760-4ead-82c4-7d0cfe651e20

	measure OrdersProductsDistinct =
			
			
			VAR ProductsOrders = DISTINCTCOUNT(fact_order[product_id])
			
			RETURN ProductsOrders
		formatString: 0
		displayFolder: Metricas Fact Order
		lineageTag: 8d67592e-99be-4c29-b8cf-10c0e18c95a0

	measure MediaProdutosDistintos =
			
			DIVIDE([GMVTotal],[OrdersProductsDistinct],0)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Metricas Fact Order
		lineageTag: 776209f8-e865-4df8-bca6-f5b0e27516f1

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure MedianaProdutos = ```
			
			VAR TabelaProdutos = 
			    SUMMARIZE(
			        fact_order,
			        fact_order[product_id],
			        "VendasProdutos", SUM(fact_order[revenue]) 
			    )
			RETURN 
			    MEDIANX(TabelaProdutos, [VendasProdutos])
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Metricas Fact Order
		lineageTag: 79093006-e402-4564-8fc8-89143272d77d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure MaximumGauge = 6000000
		formatString: 0
		displayFolder: Metricas Fact Order
		lineageTag: bb50d730-2ad5-4487-9d81-df223ad4dbd1

	column order_id
		dataType: int64
		formatString: 0
		lineageTag: b81fa551-3fd3-4d19-a4c3-2296fa44723b
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = User

	column order_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 68e9519a-3460-4267-9ae8-a705469c8217
		summarizeBy: none
		sourceColumn: order_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column user_id
		dataType: int64
		formatString: 0
		lineageTag: a15824ce-684c-4739-8e85-4e17f2262d55
		summarizeBy: none
		sourceColumn: user_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: 12993a0b-7c22-42a2-b760-7fb45171ed21
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column revenue
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 75df3abb-6431-4557-a07c-7c991bedc64c
		summarizeBy: none
		sourceColumn: revenue

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	partition fact_order = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\laios\Documents\Data Analyst\PowerBI\orders.xlsx"), null, true),
				    orders_Sheet = Source{[Item="orders",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(orders_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"order_id", Int64.Type}, {"order_date", type date}, {"user_id", Int64.Type}, {"product_id", Int64.Type}, {"revenue", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

